/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-04 21:11:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/styles.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/navbar.js\"></script>\r\n");
      out.write("<script src=\"js/newsjs.js\"></script>\r\n");
      out.write("<title>VishwaBank</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<a href=\"index.jsp\" class=\"logo\"><img\r\n");
      out.write("			src=\"images/VishwaBankLogo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("			<li><a href=\"#\">News</a></li>\r\n");
      out.write("			<li><a href=\"#\">Careers</a></li>\r\n");
      out.write("			<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- <section class=\"mainPoster\" style=\"background-image: url('images/galaxy3.jpg');\">\r\n");
      out.write("        <h1>TO THE FUTURE..</h1>\r\n");
      out.write("    </section> -->\r\n");
      out.write("\r\n");
      out.write("	<section class=\"mainPoster\">\r\n");
      out.write("		<video autoplay loop muted class=\"mainPostervd\">\r\n");
      out.write("			<source src=\"images/galaxy.mp4\" type=\"video/mp4\">\r\n");
      out.write("		</video>\r\n");
      out.write("		<h1>TO THE FUTURE..</h1>\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"bankanytime\"\r\n");
      out.write("		style=\"background-image: url('images/online.jpg');\">\r\n");
      out.write("		<h1>\r\n");
      out.write("			Bank anytime, anywhere with <br>VishwaBank Online\r\n");
      out.write("		</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"bankanytimedetails\">\r\n");
      out.write("			<p>\r\n");
      out.write("				Introducing the all-new, feature-packed, <br>more personalized\r\n");
      out.write("				online banking experience. <br> Weâve reimagined the online\r\n");
      out.write("				banking experience <br>to bring you more capability and insight\r\n");
      out.write("				<br>into your day-to-day financial management <br>with\r\n");
      out.write("				some exciting new tools. <br>Online Banking is the free, <br>secure\r\n");
      out.write("				way to manage your finances online <br>from any web-enabled\r\n");
      out.write("				device from anywhere <br>you have access to the Internet.\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<a href=\"login.jsp\"><button class=\"mainloginbtn\">Login</button></a> <a\r\n");
      out.write("			href=\"register.jsp\"><button class=\"mainloginbtn\">Register</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"credit\"\r\n");
      out.write("		style=\"background-image: url('images/credit.jpg');\">\r\n");
      out.write("		<h1>Choose the Card that fits you</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"ccard\">\r\n");
      out.write("			<img src=\"images/goldcd.jpg\" alt=\"\"> <img\r\n");
      out.write("				src=\"images/debitcd.jpg\" alt=\"\"> <img src=\"images/visacd.jpg\"\r\n");
      out.write("				alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"latestnews\">\r\n");
      out.write("		<h1>Latest News</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"slider\">\r\n");
      out.write("			<img class=\"sliderimg\" src=\"images/news/news1.png\" alt=\"\"\r\n");
      out.write("				onload=\"myVar = setTimeout(loadimage1, 5000)\"> <img\r\n");
      out.write("				class=\"sliderimg\" src=\"images/news/news2.png\" alt=\"\"\r\n");
      out.write("				onload=\"myVar = setTimeout(loadimage2, 10000)\"> <img\r\n");
      out.write("				class=\"sliderimg\" src=\"images/news/news3.png\" alt=\"\"\r\n");
      out.write("				onload=\"myVar = setTimeout(loadimage3, 15000)\"> <img\r\n");
      out.write("				class=\"sliderimg\" src=\"images/news/news1.png\" alt=\"\"\r\n");
      out.write("				onload=\"myVar = setTimeout(loadimage4, 20000)\"> <img\r\n");
      out.write("				class=\"sliderimg\" src=\"images/news/news2.png\" alt=\"\"\r\n");
      out.write("				onload=\"myVar = setTimeout(loadimage5, 25000)\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"forjavascript\" onload=\"sliderfunc()\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"footer-col\">\r\n");
      out.write("					<h4>company</h4>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Home</a></li>\r\n");
      out.write("						<li><a href=\"#\">our services</a></li>\r\n");
      out.write("						<li><a href=\"#\">privacy policy</a></li>\r\n");
      out.write("						<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-col\">\r\n");
      out.write("					<h4>get help</h4>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-col\">\r\n");
      out.write("					<h4>online Banking</h4>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Online Banking Portal</a></li>\r\n");
      out.write("						<li><a href=\"#\">Help</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-col\">\r\n");
      out.write("					<h4>follow us</h4>\r\n");
      out.write("					<div class=\"social-links\">\r\n");
      out.write("						<a href=\"#\"><img src=\"images/facebook (1).svg\" alt=\"\"></a> <a\r\n");
      out.write("							href=\"#\"><img src=\"images/instagram.svg\" alt=\"\"></a> <a\r\n");
      out.write("							href=\"#\"><img src=\"images/linkedin.svg\" alt=\"\"></a> <a\r\n");
      out.write("							href=\"#\"><img src=\"images/twitter.svg\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
